services:

  mongo_db:
    image: mongo
    container_name: mongodb_soundlog
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis_soundlog
    restart: always
    ports:
    -  "6379:6379"

volumes:
  mongo_data:




